#!/bin/bash

# Path to the requirements.txt file
REQUIREMENTS_FILE="requirements/requirements.txt"

# Check if Python is installed
if ! command -v python3 &> /dev/null
then
    echo "Python is not installed. Please install Python before proceeding."
    exit 1
fi

# Check if pip is installed
if ! command -v pip3 &> /dev/null
then
    echo "pip is not installed. Installing pip..."
    curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
    python3 get-pip.py
    rm get-pip.py
fi

# Install dependencies from requirements.txt
echo "Installing dependencies from requirements.txt..."
pip3 install -r $REQUIREMENTS_FILE

echo "Dependencies installed successfully!"
